In [23]:
import numpy as np

In [24]:
my_list =[1,2,3]

In [25]:
my_list

[1, 2, 3]

In [26]:
arr = np.array(my_list)

In [27]:
arr

array([1, 2, 3])

In [28]:
my_math = [[1,2,3],[4,5,6],[7,8,9]]

In [29]:
np.array(my_math)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
np.arange(2,10,2)

array([2, 4, 6, 8])

In [31]:
np.zeros(4)

array([0., 0., 0., 0.])

In [32]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [33]:
np.ones(3)

array([1., 1., 1.])

In [34]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

np.linespace(0,5,10);

In [39]:
np.linspace(0,5,3)

array([0. , 2.5, 5. ])

In [40]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [41]:
np.random.rand(5)

array([0.60769824, 0.17193889, 0.78864066, 0.11727623, 0.7836779 ])

In [43]:
np.random.rand(3,3)

array([[0.8348206 , 0.25931761, 0.08029964],
       [0.97994707, 0.70105764, 0.73221895],
       [0.83386148, 0.40406418, 0.36511569]])

In [46]:
np.random.randint(0,100,10)

array([19, 87,  4, 86, 29, 78, 76, 46, 60, 68])

In [55]:
r = np.arange(25)

In [56]:
r

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [57]:
r.max()

np.int64(24)

In [58]:
r.min

<function ndarray.min(axis=None, out=None, **kwargs)>

In [59]:
r.min()

np.int64(0)

In [60]:
r.argmax()

np.int64(24)

In [61]:
r.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [62]:
r.dtype()

TypeError: 'numpy.dtypes.Int64DType' object is not callable