In [3]:
import numpy as np

In [4]:
my_list =[1,2,3]

In [5]:
my_list

[1, 2, 3]

In [6]:
arr = np.array(my_list)

In [7]:
arr

array([1, 2, 3])

In [8]:
my_math = [[1,2,3],[4,5,6],[7,8,9]]

In [9]:
np.array(my_math)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
np.arange(2,10,2)

array([2, 4, 6, 8])

In [11]:
np.zeros(4)

array([0., 0., 0., 0.])

In [12]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.ones(3)

array([1., 1., 1.])

In [14]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

np.linespace(0,5,10);

In [15]:
np.linspace(0,5,3)

array([0. , 2.5, 5. ])

In [16]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [17]:
np.random.rand(5)

array([0.33994065, 0.14219599, 0.54018426, 0.27704808, 0.04790074])

In [18]:
np.random.rand(3,3)

array([[0.16289993, 0.55048065, 0.07058475],
       [0.34645939, 0.32850409, 0.5818942 ],
       [0.26612533, 0.65493454, 0.31362825]])

In [19]:
np.random.randint(0,100,10)

array([22, 74, 89, 77, 70, 62,  4, 59, 85, 21])

In [20]:
r = np.arange(25)

In [21]:
r

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [22]:
r.max()

np.int64(24)

In [23]:
r.min

<function ndarray.min(axis=None, out=None, **kwargs)>

In [24]:
r.min()

np.int64(0)

In [25]:
r.argmax()

np.int64(24)

In [26]:
r.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [27]:
arr = np.arange(0,20)

In [28]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [29]:
arr[9]

np.int64(9)

In [30]:
arr[:9]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [31]:
arr[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [32]:
arr[8:]

array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [33]:
slice_of_arry = arr[0:10]

In [34]:
slice_of_arry

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
#We do some changes

In [36]:
slice_of_arry[0:5]=100

In [37]:
slice_of_arry

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9])

In [38]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19])

In [39]:
arr_cop = arr.copy()

In [40]:
arr_cop

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19])

In [41]:
arr_cop[0:2]= 200

In [42]:
arr_cop

array([200, 200, 100, 100, 100,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19])

In [43]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19])

In [44]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [45]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [46]:
arr_2d[0][2]

np.int64(15)

In [47]:
arr_2d[1:,1:]

array([[25, 30],
       [40, 45]])

In [48]:
arr = np.arange(0,10)

In [49]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
bool_arr = arr >5

In [51]:
bool_arr

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [52]:
arr[bool_arr]

array([6, 7, 8, 9])

In [53]:
arr[arr>3]

array([4, 5, 6, 7, 8, 9])

In [54]:
arr_2d = np.arange(50).reshape(5,10)

In [55]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [56]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [57]:
arr_2d[3:5,3:5]

array([[33, 34],
       [43, 44]])